apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlbatch-system

resources:
- "https://github.com/kubeflow/training-operator/manifests/base?ref=v1.7.0"

labels:
- pairs:
    app.kubernetes.io/name: training-operator
    app.kubernetes.io/component: controller
  includeSelectors: true

images:
- name: kubeflow/training-operator
  newTag: "v1-855e096"

patches:
- path: manager_resources_patch.yaml
