# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 1 worker node
nodes:
# the control plane node config
- role: control-plane
  # kubernetes version 1.27.17 from kind v0.24.0
  image: kindest/node:v1.27.17@sha256:3fd82731af34efe19cd54ea5c25e882985bafa2c9baefe14f8deab1737d9fabe
# the worker
- role: worker
  # kubernetes version 1.27.17 from kind v0.24.0
  image: kindest/node:v1.27.17@sha256:3fd82731af34efe19cd54ea5c25e882985bafa2c9baefe14f8deab1737d9fabe
