apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-operator
spec:
  template:
    spec:
      priorityClassName: system-node-critical
      containers:
      - name:  training-operator
        args:
        - "--zap-log-level=2"
        - "--gang-scheduler-name=scheduler-plugins-scheduler"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 1000Mi
