apiVersion: workload.codeflare.dev/v1beta2
kind: AppWrapper
metadata:
  generateName: large
  labels:
    kueue.x-k8s.io/queue-name: default-queue
  annotations:
    workload.codeflare.dev.appwrapper/retryPausePeriodDuration: 5s
spec:
  components:
  - template:
      apiVersion: batch/v1
      kind: Job
      metadata:
        generateName: large
      spec:
        completions: 4
        parallelism: 4
        template:
          spec:
            restartPolicy: Never
            terminationGracePeriodSeconds: 0            
            containers:
            - name: busybox
              image: quay.io/project-codeflare/busybox:1.36
              command: ["sh", "-c", "sleep 600"]
              resources:
                limits:
                  nvidia.com/gpu: 4
