apiVersion: workload.codeflare.dev/v1beta2
kind: AppWrapper
metadata:
  generateName: normal
  labels:
    kueue.x-k8s.io/queue-name: default-queue
spec:
  components:
  - template:
      apiVersion: batch/v1
      kind: Job
      metadata:
        generateName: normal
      spec:
        completions: 2
        parallelism: 2
        template:
          spec:
            restartPolicy: Never
            terminationGracePeriodSeconds: 0            
            containers:
            - name: busybox
              image: quay.io/project-codeflare/busybox:1.36
              command: ["sh", "-c", "sleep 600"]
              resources:
                limits:
                  nvidia.com/gpu: 4
