apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-applications
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeflare-operator-config
  namespace: redhat-ods-applications
data:
  config.yaml: |
    appwrapper:
      enabled: true
      Config:
        autopilot:
          injectAntiAffinities: true
          monitorNodes: true
          resourceTaints:
            nvidia.com/gpu:
            - key: autopilot.ibm.com/gpuhealth
              value: ERR
              effect: NoSchedule
            - key: autopilot.ibm.com/gpuhealth
              value: TESTING
              effect: NoSchedule
            - key: autopilot.ibm.com/gpuhealth
              value: EVICT
              effect: NoExecute
        defaultQueueName: default-queue
        enableKueueIntegrations: true
        kueueJobReconciller:
          manageJobsWithoutQueueName: true
          waitForPodsReady:
            blockAdmission: false
            enable: false
        schedulerName: scheduler-plugins-scheduler
        slackQueueName: slack-cluster-queue
        userRBACAdmissionCheck: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlbatch-kueue
  namespace: redhat-ods-operator
data:
  controller_manager_config.yaml: |
    apiVersion: config.kueue.x-k8s.io/v1beta1
    kind: Configuration
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: :8443
      enableClusterQueueResources: true
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: c1f6bfd2.kueue.x-k8s.io
    controller:
      groupKindConcurrency:
        Job.batch: 5
        Pod: 5
        Workload.kueue.x-k8s.io: 5
        LocalQueue.kueue.x-k8s.io: 1
        Cohort.kueue.x-k8s.io: 1
        ClusterQueue.kueue.x-k8s.io: 1
        ResourceFlavor.kueue.x-k8s.io: 1
    clientConnection:
      qps: 50
      burst: 100
    #pprofBindAddress: :8082
    waitForPodsReady:
      enable: false
      blockAdmission: false
    manageJobsWithoutQueueName: true
    #managedJobsNamespaceSelector:
    #  matchLabels:
    #    kueue-managed: "true"
    #internalCertManagement:
    #  enable: false
    #  webhookServiceName: ""
    #  webhookSecretName: ""
    integrations:
      frameworks:
    # - "batch/job"
      - "kubeflow.org/mpijob"
      - "ray.io/rayjob"
      - "ray.io/raycluster"
      - "jobset.x-k8s.io/jobset"
      - "kubeflow.org/mxjob"
      - "kubeflow.org/paddlejob"
      - "kubeflow.org/pytorchjob"
      - "kubeflow.org/tfjob"
      - "kubeflow.org/xgboostjob"
    # - "pod"
    #  - "deployment" # requires enabling pod integration
    #  - "statefulset" # requires enabling pod integration
      externalFrameworks:
      - "AppWrapper.v1beta2.workload.codeflare.dev"
    # podOptions:
    #   namespaceSelector:
    #     matchExpressions:
    #       - key: kubernetes.io/metadata.name
    #         operator: NotIn
    #         values: [ kube-system, kueue-system ]
    fairSharing:
      enable: true
      preemptionStrategies: [LessThanOrEqualToFinalShare, LessThanInitialShare]
    #resources:
    #  excludeResourcePrefixes: []
    #  transformations:
    #  - input: nvidia.com/mig-4g.5gb
    #    strategy: Replace | Retain
    #    outputs:
    #      example.com/accelerator-memory: 5Gi
    #      example.com/accelerator-gpc: 4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlbatch-training-operator
  namespace: redhat-ods-operator
data:
  manager_config_patch.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: training-operator
    spec:
      template:
        spec:
          containers:
          - name:  training-operator
            image: $(image)
            args:
            - "--zap-log-level=2"
            - --pytorch-init-container-image
            - $(image)
            - "--webhook-secret-name"
            - "kubeflow-training-operator-webhook-cert"
            - "--webhook-service-name"
            - "kubeflow-training-operator"
            - "--gang-scheduler-name=scheduler-plugins-scheduler"
          volumes:
          - name: cert
            secret:
              defaultMode: 420
              secretName: kubeflow-training-operator-webhook-cert
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
spec:
  channel: fast
  installPlanApproval: Manual
  name: rhods-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhods-operator.2.21.0
  config:
    env:
    - name: "DISABLE_DSC_CONFIG"
    volumeMounts:
    - name: mlbatch-kueue
      mountPath: /opt/manifests/kueue/components/manager/controller_manager_config.yaml
      subPath: controller_manager_config.yaml
    - name: mlbatch-training-operator
      mountPath: /opt/manifests/trainingoperator/rhoai/manager_config_patch.yaml
      subPath: manager_config_patch.yaml
    volumes:
    - name: mlbatch-kueue
      configMap:
        name: mlbatch-kueue
    - name: mlbatch-training-operator
      configMap:
        name: mlbatch-training-operator
