apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlbatch-system

resources:
- ../base

patches:
- target:
    kind: Deployment
    name: training-operator
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--gang-scheduler-name=sakkara-scheduler"
