apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  name: mlbatch-dsci
spec:
  applicationsNamespace: redhat-ods-applications
  monitoring:
    managementState: Managed
    namespace: redhat-ods-monitoring
  serviceMesh:
    managementState: Removed
  trustedCABundle:
    customCABundle: ""
    managementState: Managed
