apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlbatch-system

resources:
- "https://github.com/ray-project/kuberay/ray-operator/config/default?ref=v1.1.0"

patches:
- path: remove_default_namespace.yaml
- path: manager_resources_patch.yaml
