apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlbatch-system

resources:
- "https://github.com/ray-project/kuberay/ray-operator/config/default?ref=v1.1.0"

labels:
- pairs:
    app.kubernetes.io/name: kuberay
    app.kubernetes.io/component: controller
  includeSelectors: true

patches:
- path: remove_default_namespace.yaml
- path: manager_resources_patch.yaml
