apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mlbatch-clusterqueue-edit
rules:
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - clusterqueues
  verbs:
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mlbatch-clusterqueue-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mlbatch-clusterqueue-edit
subjects:
- kind: ServiceAccount
  name: codeflare-operator-controller-manager
  namespace: redhat-ods-applications
