apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberay-operator
  namespace: system
spec:
  template:
    spec:
      priorityClassName: system-node-critical
      containers:
      - name:  kuberay-operator
        args:
        - "--zap-log-level=2"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 1000Mi
