apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scheduler-plugins.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scheduler-plugins.labels" . | nindent 4 }}
data:
  scheduler-config.yaml: |
    apiVersion: {{ .Values.schedulerConfig.apiVersion }}
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: {{ .Values.scheduler.leaderElect }}
      resourceName: {{ include "scheduler-plugins.fullname" . }}
    profiles:
    # Compose all plugins in one profile
    - schedulerName: {{ include "scheduler-plugins.fullname" . }}
      plugins:
        {{- toYaml $.Values.plugins | nindent 8 }}
      {{- if $.Values.pluginConfig }}
      pluginConfig: {{ toYaml $.Values.pluginConfig | nindent 6 }}
{{- end }}
