---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scheduler-plugins.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scheduler-plugins.labels" . | nindent 4 }}
