name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Set latest tag and branch name
      run: |
        echo "GIT_BRANCH=gha-ci" >> $GITHUB_ENV
        echo "TAG=$GITHUB_RUN_ID" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Install Helm unittest plugin
      run: |
        helm plugin install https://github.com/helm-unittest/helm-unittest.git

    - name: Run pre-commit checks
      run: |
        pip install pre-commit
        pre-commit run --show-diff-on-failure --color=always --all-files

