name: Release Charts

on:
  # This workflow is meant to be triggered manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Publish PyTorchJob Generator Helm Chart
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: tools/pytorchjob-generator
          packages_with_index: true
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish Sakkara Scheduler Helm Chart
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: sakkara-deploy/install
          packages_with_index: true
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  publish:
    needs: release
    uses: project-codeflare/mlbatch/.github/workflows/gh-pages-static.yml@main
